name: Step 2 - Recieve Application T rigger 
on: 
  repository_dispatch:
    types:
      - application_push


jobs:
   recieve-trigger:
      name: Verify Cross-Repo Communication
      runs-on: ubuntu-latest


      steps:
        - name: Display Recieved application Information 
          run:
            echo "SecOps Repo recieved Application trigger"
            echo " Application Repository:${{ github.event.client_payload.repository }}"
            echo " Application Branch:${{ github.event.client_payload.branch }}"
            echo " Application Commit SHA:${{ github.event.client_payload.commit_sha }}"